# -*- coding: utf-8 -*-
"""Input_SHAP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fEiL73k29dtBmOLtztFYxdIuc8BM_G0v

# Dataset

Dataset diperoleh dari platform GitHub: https://github.com/mhd-luqmaan/Statistical-Analysis-of-a-Tuberculosis-Patient-Dataset----Using-python

# Data Loading
"""

from google.colab import drive
# Mount Google Drive ke mount point standar '/content/drive'
drive.mount('/content/drive')

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Dataset/tuberculosis_xray_dataset.csv')

df.head()

"""# Data Exploration"""

#Meninjau jumlah baris dan kolom dataset
jumlah_baris, jumlah_kolom = df.shape

print(f"Jumlah baris (rows): {jumlah_baris}")
print(f"Jumlah kolom (columns): {jumlah_kolom}")

#Menampilkan informasi dataset
df.info()

# 2. Check the data types of each column in `df`
print("\nData types of each column:")
display(df.dtypes)

# 3. Identify any missing values in `df` and count them per column
print("\nMissing values per column:")
display(df.isnull().sum())

# Identifikasi baris duplikat
duplicate_rows = df[df.duplicated()]

# Hitung jumlah baris duplikat
num_duplicates = duplicate_rows.shape[0]

print(f"Jumlah baris duplikat yang ditemukan: {num_duplicates}")

if num_duplicates > 0:
    print("\nBeberapa baris duplikat pertama:")
    display(duplicate_rows.head())
else:
    print("Tidak ada baris duplikat yang ditemukan dalam dataset.")

# 4. Display summary statistics for the numerical columns in `df`
print("\nSummary statistics for numerical columns:")
display(df.describe())

# 5. Display summary statistics for the categorical columns in `df`
print("\nSummary statistics for categorical columns:")
display(df.describe(include='object'))

import matplotlib.pyplot as plt
import seaborn as sns

numerical_cols = ['Age', 'Cough_Severity', 'Breathlessness', 'Fatigue', 'Weight_Loss']
categorical_cols = ['Gender', 'Chest_Pain', 'Fever', 'Night_Sweats', 'Sputum_Production', 'Blood_in_Sputum', 'Smoking_History', 'Previous_TB_History', 'Class']

# 1. Calculate and display descriptive statistics for numerical columns
print("Descriptive statistics for numerical columns:")
display(df[numerical_cols].describe())

# 2. Generate histograms for numerical columns
print("\nHistograms for numerical columns:")
plt.figure(figsize=(15, 10))
for i, col in enumerate(numerical_cols):
    plt.subplot(2, 3, i + 1)
    sns.histplot(data=df, x=col, kde=True)
    plt.title(f'Distribution of {col}')
    plt.xlabel(col)
    plt.ylabel('Frequency')
plt.tight_layout()
plt.show()

# 3. Create box plots for numerical columns
print("\nBox plots for numerical columns:")
plt.figure(figsize=(15, 10))
for i, col in enumerate(numerical_cols):
    plt.subplot(2, 3, i + 1)
    sns.boxplot(data=df, y=col)
    plt.title(f'Box plot of {col}')
    plt.ylabel(col)
plt.tight_layout()
plt.show()

# 4. Generate count plots for categorical columns
print("\nCount plots for categorical columns:")
plt.figure(figsize=(20, 15))
for i, col in enumerate(categorical_cols):
    plt.subplot(3, 3, i + 1)
    sns.countplot(data=df, x=col)
    plt.title(f'Count of {col}')
    plt.xlabel(col)
    plt.ylabel('Count')
    plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

# 5. Create grouped box plot of Age vs. Class
print("\nBox plot of Age by Class:")
plt.figure(figsize=(8, 6))
sns.boxplot(data=df, x='Class', y='Age')
plt.title('Distribution of Age by Class')
plt.xlabel('Class')
plt.ylabel('Age')
plt.show()

import numpy as np
# Pairplot untuk hubungan antar variabel numerikal
sns.pairplot(df.select_dtypes(include=[np.number]))
plt.suptitle("Pairplot Antar Variabel Numerik", y=1.02)
plt.show()

"""# Data Preparation

## Menghapus Kolom Yang Tidak Diperlukan
"""

df = df.drop(columns=['Patient_ID'])

pd.set_option('future.no_silent_downcasting', True)

# Gender Mapping
gender_mapping = {
    'Male': 0,
    'Female': 1
}
df['Gender'] = df['Gender'].replace(gender_mapping).infer_objects(copy=False)

# Yes No Mapping
yes_no_mapping = {
    'No': 0,
    'Yes': 1
}
df['Chest_Pain'] = df['Chest_Pain'].replace(yes_no_mapping).infer_objects(copy=False)
df['Night_Sweats'] = df['Night_Sweats'].replace(yes_no_mapping).infer_objects(copy=False)
df['Blood_in_Sputum'] = df['Blood_in_Sputum'].replace(yes_no_mapping).infer_objects(copy=False)
df['Previous_TB_History'] = df['Previous_TB_History'].replace(yes_no_mapping).infer_objects(copy=False)

from sklearn.preprocessing import LabelEncoder

label_encoders = {}

# List kolom yang perlu diencode (disesuaikan dengan DataFrame yang ada)
categorical_cols = ['Fever', 'Sputum_Production', 'Smoking_History', 'Class']

# Encode setiap kolom kategorikal ke numerik
for col in categorical_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le  # Simpan encoder untuk setiap kolom

df.head()

df.info()

print(df['Class'].value_counts())

from sklearn.model_selection import train_test_split

label_counts = df['Class'].value_counts()
valid_labels = label_counts[label_counts >= 9].index

filtered_df = df[df['Class'].isin(valid_labels)]

X = filtered_df.drop(columns=['Class'])
y = filtered_df['Class']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print("Jumlah data pelatihan:", len(X_train))
print("Jumlah data pengujian:", len(X_test))

"""# Modelling

## Latih Model Dengan Random Forest
"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

model = RandomForestClassifier(n_estimators=50, random_state=42, max_depth=15)
model.fit(X_train, y_train)

"""## Latih Model Dengan XGBoost"""

from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, f1_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

# 1. Label Encoding (jika target tidak mulai dari 0)
le = LabelEncoder()
y_encoded = le.fit_transform(y)

# 2. Split data
X_train, X_test, y_train, y_test = train_test_split(
    X, y_encoded, test_size=0.2, stratify=y_encoded, random_state=42)

# Inisialisasi model XGBoost
xgb_model = XGBClassifier(
    objective='multi:softmax',
    num_class=len(le.classes_),
    eval_metric='mlogloss',
    use_label_encoder=False,
    random_state=42
)

# Latih model
xgb_model.fit(X_train, y_train)

"""# Evaluation

## Evaluasi Model Random Forest
"""

from sklearn.metrics import accuracy_score, f1_score, classification_report, confusion_matrix

# Evaluasi
y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

rf_train_acc = accuracy_score(y_train, y_train_pred)
rf_test_acc = accuracy_score(y_test, y_test_pred)

print("\nRandom Forest - Training Report:")
print(classification_report(y_train, y_train_pred))

print("\nRandom Forest - Training Confusion Matrix:")
cm_train_rf = confusion_matrix(y_train, y_train_pred)
print(cm_train_rf)
TN_train_rf, FP_train_rf, FN_train_rf, TP_train_rf = cm_train_rf.ravel()
print(f"Training - True Positives (TP): {TP_train_rf}")
print(f"Training - True Negatives (TN): {TN_train_rf}")
print(f"Training - False Positives (FP): {FP_train_rf}")
print(f"Training - False Negatives (FN): {FN_train_rf}")

print("\nRandom Forest - Testing Report:")
print(classification_report(y_test, y_test_pred))

print("\nRandom Forest - Testing Confusion Matrix:")
cm_test_rf = confusion_matrix(y_test, y_test_pred)
print(cm_test_rf)
TN_test_rf, FP_test_rf, FN_test_rf, TP_test_rf = cm_test_rf.ravel()
print(f"Testing - True Positives (TP): {TP_test_rf}")
print(f"Testing - True Negatives (TN): {TN_test_rf}")
print(f"Testing - False Positives (FP): {FP_test_rf}")
print(f"Testing - False Negatives (FN): {FN_test_rf}")

"""## Evaluasi Model XGBoost"""

from sklearn.metrics import accuracy_score, f1_score, classification_report, confusion_matrix

# 5. Evaluasi model
y_train_pred = xgb_model.predict(X_train)
y_test_pred = xgb_model.predict(X_test)

xgb_train_acc = accuracy_score(y_train, y_train_pred)
xgb_test_acc = accuracy_score(y_test, y_test_pred)

print("\nXGBoost - Training Report:")
print(classification_report(y_train, y_train_pred))

print("\nXGBoost - Training Confusion Matrix:")
cm_train_xgb = confusion_matrix(y_train, y_train_pred)
print(cm_train_xgb)
TN_train_xgb, FP_train_xgb, FN_train_xgb, TP_train_xgb = cm_train_xgb.ravel()
print(f"Training - True Positives (TP): {TP_train_xgb}")
print(f"Training - True Negatives (TN): {TN_train_xgb}")
print(f"Training - False Positives (FP): {FP_train_xgb}")
print(f"Training - False Negatives (FN): {FN_train_xgb}")

print("\nXGBoost - Testing Report:")
print(classification_report(y_test, y_test_pred))

print("\nXGBoost - Testing Confusion Matrix:")
cm_test_xgb = confusion_matrix(y_test, y_test_pred)
print(cm_test_xgb)
TN_test_xgb, FP_test_xgb, FN_test_xgb, TP_test_xgb = cm_test_xgb.ravel()
print(f"Testing - True Positives (TP): {TP_test_xgb}")
print(f"Testing - True Negatives (TN): {TN_test_xgb}")
print(f"Testing - False Positives (FP): {FP_test_xgb}")
print(f"Testing - False Negatives (FN): {FN_test_xgb}")

"""# Tunning

## Tunning Model Random Forest
"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import RandomizedSearchCV

rf_param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [5, 10, 15],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

rf = RandomForestClassifier(random_state=42)
rf_search = RandomizedSearchCV(rf, rf_param_grid, n_iter=10, cv=3, scoring='accuracy', random_state=42, n_jobs=-1)
rf_search.fit(X_train, y_train)

print("Best RF Params:", rf_search.best_params_)
print("Best RF Score:", rf_search.best_score_)

"""## Tunning Model XGBoost"""

from xgboost import XGBClassifier

xgb_param_grid = {
    'n_estimators': [100, 200],
    'max_depth': [3, 5, 7],
    'learning_rate': [0.01, 0.1, 0.2],
    'subsample': [0.6, 0.8, 1.0]
}

xgb = XGBClassifier(random_state=42, use_label_encoder=False, eval_metric='mlogloss')
xgb_search = RandomizedSearchCV(xgb, xgb_param_grid, n_iter=10, cv=3, scoring='accuracy', random_state=42, n_jobs=-1)
xgb_search.fit(X_train, y_train)

print("Best XGB Params:", xgb_search.best_params_)
print("Best XGB Score:", xgb_search.best_score_)

"""# Testing

## Testing Statis
"""

# Ambil baris pertama dari X_test sebagai input terenkripsi
input_df_encoded = X_test.iloc[[0]]

# Dapatkan indeks baris asli
original_index = input_df_encoded.index[0]

# Dapatkan data input asli (sebelum encoding) dari DataFrame df
input_df_original = df.loc[[original_index]]

print("Data input asli (sebelum encoding):\n", input_df_original.drop(columns=['Class'])) # Drop 'Class' for input display

# Assign the best model (e.g., from Random Forest tuning) to best_model
best_model = xgb_search.best_estimator_

# Prediksi menggunakan data terenkripsi
prediksi_numeric = best_model.predict(input_df_encoded)

# Ubah prediksi numerik kembali ke label kategorikal
predicted_class_label = label_encoders['Class'].inverse_transform(prediksi_numeric)[0]

print("Hasil prediksi (label):", predicted_class_label)

"""## Testing Dinamis oleh User"""

import pandas as pd

def get_user_input():
    user_input = {}
    print("\nMasukkan data pasien secara manual:\n")

    user_input['Age'] = int(input("Umur (tahun): "))

    gender_map_rev = {v: k for k, v in gender_mapping.items()}
    print(f"Jenis Kelamin ({list(gender_map_rev.values())}): ")
    user_input['Gender'] = gender_mapping[input().strip().capitalize()]

    yes_no_map_rev = {v: k for k, v in yes_no_mapping.items()}
    print(f"Nyeri Dada ({list(yes_no_map_rev.values())}): ")
    user_input['Chest_Pain'] = yes_no_mapping[input().strip().capitalize()]

    user_input['Cough_Severity'] = int(input("Tingkat Keparahan Batuk (0-9): "))
    user_input['Breathlessness'] = int(input("Sesak Nafas (0-9): "))
    user_input['Fatigue'] = int(input("Kelelahan (0-9): "))
    user_input['Weight_Loss'] = float(input("Penurunan Berat Badan (kg): "))

    fever_classes = list(label_encoders['Fever'].classes_)
    print(f"Demam ({fever_classes}): ")
    user_input['Fever'] = label_encoders['Fever'].transform([input().strip().capitalize()])[0]

    print(f"Keringat Malam ({list(yes_no_map_rev.values())}): ")
    user_input['Night_Sweats'] = yes_no_mapping[input().strip().capitalize()]

    sputum_classes = list(label_encoders['Sputum_Production'].classes_)
    print(f"Produksi Dahak ({sputum_classes}): ")
    user_input['Sputum_Production'] = label_encoders['Sputum_Production'].transform([input().strip().capitalize()])[0]

    print(f"Darah dalam Dahak ({list(yes_no_map_rev.values())}): ")
    user_input['Blood_in_Sputum'] = yes_no_mapping[input().strip().capitalize()]

    smoking_classes = list(label_encoders['Smoking_History'].classes_)
    print(f"Riwayat Merokok ({smoking_classes}): ")
    user_input['Smoking_History'] = label_encoders['Smoking_History'].transform([input().strip().capitalize()])[0]

    print(f"Riwayat Tuberkulosis Sebelumnya ({list(yes_no_map_rev.values())}): ")
    user_input['Previous_TB_History'] = yes_no_mapping[input().strip().capitalize()]

    return user_input

# Dapatkan input dari user
manual_input = get_user_input()

# Buat DataFrame dari input user
# Pastikan urutan kolom sesuai dengan X_train
input_df_manual = pd.DataFrame([manual_input], columns=X_train.columns)

print("\nInput yang diproses untuk prediksi:")
display(input_df_manual)

# Lakukan prediksi
manual_prediction_numeric = best_model.predict(input_df_manual)

# Ubah prediksi numerik kembali ke label kategorikal
manual_predicted_class_label = label_encoders['Class'].inverse_transform(manual_prediction_numeric)[0]

print(f"\nHasil Prediksi Model: {manual_predicted_class_label}")

"""# Metode Shap"""

import shap
import pandas as pd

# Pastikan manual_input_df sudah dibuat dari input user
# Jika cell sebelumnya belum dijalankan atau `input_df_manual` tidak ada, perlu dijalankan lagi.
# Misalnya:
# from sklearn.preprocessing import LabelEncoder # Pastikan ini diimpor jika belum
# # Dapatkan input dari user (gunakan fungsi get_user_input() yang sudah didefinisikan)
# manual_input = get_user_input()
# input_df_manual = pd.DataFrame([manual_input], columns=X_train.columns)

print("\nMenghitung SHAP values untuk input manual...")

# Menggunakan TreeExplainer karena kita menggunakan RandomForest atau XGBoost
explainer = shap.TreeExplainer(best_model)
shap_values = explainer.shap_values(input_df_manual)

# Determine the class for which to plot SHAP values
predicted_class_index = manual_prediction_numeric[0] # Get the numerical predicted class (0 for Normal, 1 for Tuberculosis)

# Extract SHAP values and expected value for the predicted class for the first (and only) instance
if isinstance(shap_values, list): # This is typically for multi-output models like RandomForestClassifier
    # shap_values is a list where each element is an array (n_samples, n_features) for a specific class
    shap_values_for_plot = shap_values[predicted_class_index][0] # Select class, then first sample's features
    expected_value_for_plot = explainer.expected_value[predicted_class_index]
else:
    # This branch is taken if shap_values is a single 2D array (n_samples, n_features) or 3D array
    # Check if it's 2D (binary classification) or 3D (multiclass classification where output for each class is separate)
    if shap_values.ndim == 2:
        # For binary classification, shap_values is (n_samples, n_features)
        # We take the values for the first (and only) sample
        shap_values_for_plot = shap_values[0, :]
        # The expected value for binary classification might be a single value
        # or an array/list of two values. We pick the one corresponding to the predicted class.
        if isinstance(explainer.expected_value, (list, np.ndarray)):
            expected_value_for_plot = explainer.expected_value[predicted_class_index]
        else:
            expected_value_for_plot = explainer.expected_value
    elif shap_values.ndim == 3:
        # For multiclass classification, shap_values is (n_samples, n_features, n_outputs)
        shap_values_for_plot = shap_values[0, :, predicted_class_index]
        expected_value_for_plot = explainer.expected_value[predicted_class_index]
    else:
        raise ValueError("Unexpected shape for shap_values. Expected 2D or 3D.")

# --- Translate feature names to Indonesian ---
feature_name_mapping = {
    'Age': 'Usia',
    'Gender': 'Jenis Kelamin',
    'Chest_Pain': 'Nyeri Dada',
    'Cough_Severity': 'Tingkat Batuk',
    'Breathlessness': 'Sesak Napas',
    'Fatigue': 'Kelelahan',
    'Weight_Loss': 'Penurunan Berat Badan',
    'Fever': 'Demam',
    'Night_Sweats': 'Keringat Malam',
    'Sputum_Production': 'Produksi Dahak',
    'Blood_in_Sputum': 'Darah dalam Dahak',
    'Smoking_History': 'Riwayat Merokok',
    'Previous_TB_History': 'Riwayat TB Sebelumnya',
    'Class': 'Kelas'
}

translated_feature_names = [feature_name_mapping.get(col, col) for col in input_df_manual.columns]

# Construct a Series for the data parameter with translated index
data_for_explanation = pd.Series(input_df_manual.iloc[0].values, index=translated_feature_names)

print("\nSHAP Force Plot (HTML will be displayed if running in environments like Jupyter/Colab):")
shap.initjs() # For initializing JavaScript needed by SHAP plots
# Force plot can also be generated here if desired, e.g.:
# shap.force_plot(expected_value_for_plot, shap_values_for_plot, input_df_manual.iloc[0])

print("\nSHAP Waterfall Plot:")
shap.plots.waterfall(shap.Explanation(values=shap_values_for_plot,
                                     base_values=expected_value_for_plot,
                                     data=data_for_explanation,
                                     feature_names=translated_feature_names))

"""### Penjelasan Warna pada SHAP Waterfall Plot

Pada SHAP waterfall plot:

*   **Warna Merah:** Batang berwarna merah menunjukkan fitur-fitur yang **meningkatkan** probabilitas prediksi model. Dalam konteks klasifikasi (misalnya, Tuberculosis vs. Normal), fitur merah mendorong prediksi model *lebih dekat ke kelas positif* (misalnya, 'Tuberculosis'). Semakin panjang batangnya, semakin besar pengaruh positifnya.

*   **Warna Biru:** Batang berwarna biru menunjukkan fitur-fitur yang **menurunkan** probabilitas prediksi model. Fitur biru mendorong prediksi model *lebih dekat ke kelas negatif* (misalnya, 'Normal'). Semakin panjang batangnya, semakin besar pengaruh negatifnya.

Plot ini dimulai dari `base value` (nilai dasar, yaitu rata-rata prediksi model pada dataset). Kemudian, setiap batang (fitur) menambah atau mengurangi nilai tersebut sampai mencapai prediksi akhir model untuk input yang Anda berikan. Dengan demikian, Anda bisa melihat secara visual fitur mana yang paling berpengaruh dan ke arah mana pengaruhnya terhadap prediksi tertentu.
"""

print("\n--- Penjelasan SHAP Waterfall Plot Per Kolom ---\n")

# Perhatikan bahwa 'Normal' adalah label untuk kelas 0 dalam label_encoders
# Sesuaikan penjelasan berdasarkan prediksi model (Normal atau Tuberculosis)
predicted_class_for_explanation = label_encoders['Class'].inverse_transform([predicted_class_index])[0]

print(f"Base Value (E[f(X)]): {expected_value_for_plot:.2f}")
print(f"Ini adalah nilai dasar rata-rata output model (dalam skala log-odds) untuk kelas '{predicted_class_for_explanation}' di seluruh dataset. Semua kontribusi fitur bermula dari nilai ini.\n")

# Get feature names and their values for the manual input (using translated names)
feature_names_translated = translated_input_df_manual.columns.tolist()
feature_values = input_df_manual.iloc[0].values

# Create a dictionary to map original feature names to their translated names
original_to_translated_name = {original: translated for original, translated in zip(input_df_manual.columns, feature_names_translated)}

# Combine SHAP values, original feature names, and feature values for easier iteration
feature_contributions = sorted(zip(shap_values_for_plot, input_df_manual.columns, feature_values), key=lambda x: abs(x[0]), reverse=True)

for shap_val, original_feature_name, feature_val in feature_contributions:
    translated_feature_name = original_to_translated_name[original_feature_name]
    contribution_type = "meningkatkan" if shap_val > 0 else "menurunkan"
    direction = "mendukung" if shap_val > 0 else "menjauhkan"
    effect_type = "positif" if shap_val > 0 else "negatif"

    # Handle specific value mappings for better readability in explanations
    display_feature_val = feature_val
    if original_feature_name == 'Gender':
        display_feature_val = 'Laki-laki' if feature_val == 0 else 'Perempuan'
    elif original_feature_name in ['Chest_Pain', 'Night_Sweats', 'Blood_in_Sputum', 'Previous_TB_History']:
        display_feature_val = 'Ya' if feature_val == 1 else 'Tidak'
    elif original_feature_name == 'Fever':
        display_feature_val = label_encoders['Fever'].inverse_transform([int(feature_val)])[0]
    elif original_feature_name == 'Sputum_Production':
        display_feature_val = label_encoders['Sputum_Production'].inverse_transform([int(feature_val)])[0]
    elif original_feature_name == 'Smoking_History':
        display_feature_val = label_encoders['Smoking_History'].inverse_transform([int(feature_val)])[0]

    print(f"*   **{translated_feature_name} ({display_feature_val}, SHAP: {shap_val:+.2f}):**")
    print(f"    *   **Nilai Fitur:** Pasien memiliki '{translated_feature_name}' dengan nilai {display_feature_val}.")

    if abs(shap_val) > 0.005: # Threshold for significant contributions
        print(f"    *   **Kontribusi SHAP:** Ini adalah kontributor {effect_type} ({shap_val:+.2f}). Artinya, nilai {translated_feature_name} ({display_feature_val}) secara signifikan **{contribution_type}** kemungkinan prediksi pasien menjadi '{predicted_class_for_explanation}'. Ini {direction} kuat prediksi '{predicted_class_for_explanation}'.")
    elif abs(shap_val) > 0:
        print(f"    *   **Kontribusi SHAP:** Memberikan kontribusi {effect_type} ({shap_val:+.2f}). Kontribusi ini **sedikit {contribution_type}** kemungkinan prediksi '{predicted_class_for_explanation}'.")
    else:
        print(f"    *   **Kontribusi SHAP:** Kontribusinya mendekati nol ({shap_val:+.2f}). Artinya, nilai ini **hampir tidak berpengaruh** terhadap prediksi '{predicted_class_for_explanation}' untuk pasien ini.")
    print("\n")

# Calculate the final output from base value and shap values
final_output = expected_value_for_plot + sum(shap_values_for_plot)
print(f"*   **Output Akhir (f(x) = {final_output:.3f}):**")
print(f"Setelah semua kontribusi fitur digabungkan dari base value, output akhir model (log-odds) adalah {final_output:.3f}. Nilai ini mengarah pada prediksi model '{predicted_class_for_explanation}'.")

"""# Convert Model

## Konversi Model dengan scaler.pkl
"""

import joblib

# Simpan model ke file
joblib.dump(best_model, 'best_model.pkl')

# Simpan label_encoders ke file
joblib.dump(label_encoders, 'label_encoders.pkl')

# Kemudian untuk load ulang:
model = joblib.load('best_model.pkl')
label_encoders = joblib.load('label_encoders.pkl')

"""## Konversi Model Dengan Flask"""

from flask import Flask, request, jsonify
import joblib
import pandas as pd

model = joblib.load('best_model.pkl')
label_encoders = joblib.load('label_encoders.pkl')

app = Flask(__name__)

@app.route('/predict', methods=['POST'])
def predict():
    input_data = request.json
    input_df = pd.DataFrame([input_data])
    # No scaler was used during training, so no scaling is applied here
    prediction_numeric = model.predict(input_df)[0]

    # Inverse transform the numerical prediction back to its original label
    predicted_class_label = label_encoders['Class'].inverse_transform([prediction_numeric])[0]

    return jsonify({'prediction': predicted_class_label})

if __name__ == '__main__':
    app.run()