# -*- coding: utf-8 -*-
"""Shap_Percobaan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lKyMwPzS05I9IXXwO_JCECkCfgqfaZCe

# Import Library
"""

# Commented out IPython magic to ensure Python compatibility.
# Mengimpor libraries umum yang sering digunakan
import os, shutil
import zipfile
import random
from random import sample
import shutil
from shutil import copyfile
import pathlib
from pathlib import Path
import numpy as np
import pandas as pd
from tqdm.notebook import tqdm as tq

# Mengimpor libraries untuk visualisasi
# %matplotlib inline
import matplotlib.image as mpimg
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib.image import imread

# Mengimpor libraries untuk pemrosesan data gambar
import cv2
from PIL import Image
import skimage
from skimage import io
from skimage.transform import resize
from skimage.transform import rotate, AffineTransform, warp
from skimage import img_as_ubyte
from skimage.exposure import adjust_gamma
from skimage.util import random_noise

# Mengimpor libraries untuk pembuatan dan evaluasi model
import keras
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report
import tensorflow as tf
from tensorflow.keras import Model, layers
from tensorflow.keras.preprocessing import image
from tensorflow.keras.preprocessing.image import ImageDataGenerator, img_to_array, load_img
from tensorflow.keras.optimizers import Adam, RMSprop, SGD
from tensorflow.keras.layers import InputLayer, Conv2D, SeparableConv2D, MaxPooling2D, MaxPool2D, Dense, Flatten, Dropout, BatchNormalization
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.applications import MobileNet
from tensorflow.keras.applications.densenet import DenseNet121
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.callbacks import ModelCheckpoint, Callback, EarlyStopping, ReduceLROnPlateau

# Mengabaikan peringatan
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

"""# Data Loading"""

from google.colab import drive
# Mount Google Drive ke mount point standar '/content/drive'
drive.mount('/content/drive')
# Setelah berhasil di-mount, Anda bisa mengakses folder Anda di /content/drive/MyDrive/Dataset

"""## Plot Gambar Sesuai Kelas

# Data Exploration
"""

# Membuat kamus yang menyimpan nama gambar untuk setiap kelas
tb_image = {}

# Path ke direktori data
path = "drive/MyDrive/Dataset" # Path yang benar setelah unzip dataset

# Isi lung_image dengan daftar gambar dari masing-masing kelas
for class_name in os.listdir(path):
    class_path = os.path.join(path, class_name)
    if os.path.isdir(class_path):
        image_files = [img for img in os.listdir(class_path) if img.endswith(('.png', '.jpg', '.jpeg'))]
        tb_image[class_name] = image_files

# Pastikan lung_image terisi
if not tb_image:
    raise ValueError("Tidak ada data ditemukan di folder.")

# Menampilkan secara acak 5 gambar untuk setiap kelas
fig, axs = plt.subplots(len(tb_image.keys()), 5, figsize=(15, 15))

for i, (class_name, image_list) in enumerate(tb_image.items()):
    images = np.random.choice(image_list, 5, replace=False)

    for j, image_name in enumerate(images):
        img_path = os.path.join(path, class_name, image_name)
        img = Image.open(img_path).convert("L")  # Konversi ke grayscale
        axs[i, j].imshow(img, cmap='gray')
        axs[i, j].set(xlabel=class_name, xticks=[], yticks=[])

fig.tight_layout()
plt.show()

"""## Plot Distribusi Perkelas"""

# Define source path
lung_path = "drive/MyDrive/Dataset"

# Create a list that stores data for each filenames, filepaths, and labels in the data
file_name = []
labels = []
full_path = []

# Get data image filenames, filepaths, labels one by one with looping, and store them as dataframe
for path, subdirs, files in os.walk(lung_path):
    for name in files:
        full_path.append(os.path.join(path, name))
        labels.append(path.split('/')[-1])
        file_name.append(name)

distribution_train = pd.DataFrame({"path":full_path,'file_name':file_name,"labels":labels})

# Plot the distribution of images across the classes
Label = distribution_train['labels']
plt.figure(figsize = (6,6))
sns.set_style("darkgrid")
plot_data = sns.countplot(Label)

import tensorflow as tf
from tensorflow.keras.preprocessing import image
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import numpy as np
import random

# Membuat fungsi untuk melakukan rotasi berlawanan arah jarum jam
def anticlockwise_rotation(img):
    img = tf.image.resize(img, (224, 224))
    img = tf.image.rot90(img, k=random.randint(1, 4))  # Rotasi 90, 180, atau 270 derajat secara acak
    return img

# Membuat fungsi untuk melakukan rotasi searah jarum jam
def clockwise_rotation(img):
    img = tf.image.resize(img, (224, 224))
    img = tf.image.rot90(img, k=random.randint(1, 4))  # Rotasi 90, 180, atau 270 derajat secara acak
    return img

# Membuat fungsi untuk membalik gambar secara vertikal dari atas ke bawah
def flip_up_down(img):
    img = tf.image.resize(img, (224, 224))
    img = tf.image.flip_up_down(img)
    return img

# Membuat fungsi untuk memberikan efek peningkatan kecerahan pada gambar
def add_brightness(img):
    img = tf.image.resize(img, (224, 224))
    img = tf.image.adjust_brightness(img, delta=random.uniform(0.1, 0.5))  # Sesuaikan nilai delta sesuai kebutuhan
    return img

# Membuat fungsi untuk memberikan efek blur pada gambar
def blur_image(img):
    img = tf.image.resize(img, (224, 224))
    img = tf.image.random_blur(img, (3, 3))  # Ukuran kernel blur bisa disesuaikan
    return img

# Membuat fungsi untuk memberikan efek pergeseran acak pada gambar
def sheared(img):
    img = tf.image.resize(img, (224, 224))
    # Buat objek ImageDataGenerator dengan parameter shearing range
    datagen = ImageDataGenerator(shear_range=0.2)
    img = next(iter(datagen.flow(tf.expand_dims(img, 0))))[0]
    return img

# Membuat fungsi untuk melakukan pergeseran melengkung pada gambar
def warp_shift(img):
    img = tf.image.resize(img, (224, 224))
    # Buat objek ImageDataGenerator dengan parameter width_shift_range dan height_shift_range
    datagen = ImageDataGenerator(width_shift_range=0.1, height_shift_range=0.1)
    img = next(iter(datagen.flow(tf.expand_dims(img, 0))))[0]
    return img

# Define source path
cat_path = "drive/MyDrive/Dataset"

# Create a list that stores data for each filenames, filepaths, and labels in the data
file_name = []
labels = []
full_path = []

# Get data image filenames, filepaths, labels one by one with looping, and store them as dataframe
for path, subdirs, files in os.walk(cat_path):
    for name in files:
        full_path.append(os.path.join(path, name))
        labels.append(path.split('/')[-1])
        file_name.append(name)

distribution_train = pd.DataFrame({"path":full_path,'file_name':file_name,"labels":labels})

# Plot the distribution of images across the classes
Label = distribution_train['labels']
plt.figure(figsize = (6,6))
sns.set_style("darkgrid")
plot_data = sns.countplot(Label)

"""# Data Preparation"""

import pandas as pd
import os

# Panggil variabel mypath yang menampung folder dataset gambar
mypath= 'drive/MyDrive/Dataset'

file_name = []
labels = []
full_path = []
for path, subdirs, files in os.walk(mypath):
    for name in files:
        full_path.append(os.path.join(path, name))
        labels.append(path.split('/')[-1])
        file_name.append(name)


# Memasukan variabel yang sudah dikumpulkan pada looping di atas menjadi sebuah dataframe agar rapih
df = pd.DataFrame({"path":full_path,'file_name':file_name,"labels":labels})

# --- START OF FIX ---
# Filter out the 'Dataset' label which is not a true class for the model
df = df[df['labels'] != 'Dataset']

# Assign X and y after filtering to ensure they reflect the correct 3 classes
X = df['path']
y = df['labels']
# --- END OF FIX ---

# Melihat jumlah data gambar pada masing-masing label
df.groupby(['labels']).size()

# Variabel yang digunakan pada pemisahan data ini dimana variabel x = data path dan y = data labels
# X= df['path'] # Moved to previous cell
# y= df['labels'] # Moved to previous cell

# Pertama, bagi data menjadi train dan sementara (temp)
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.2, random_state=300)

# Kemudian, bagi temp menjadi test dan validation (misalnya 50% masing-masing dari temp)
X_test, X_valid, y_test, y_valid = train_test_split(X_temp, y_temp, test_size=0.5, random_state=300)

# Menyatukan kedalam masing-masing dataframe
df_tr = pd.DataFrame({'path': X_train, 'labels': y_train, 'set': 'train'})
df_valid = pd.DataFrame({'path': X_valid, 'labels': y_valid, 'set': 'validation'})
df_te = pd.DataFrame({'path': X_test, 'labels': y_test, 'set': 'test'})

# Print hasil diatas untuk melihat panjang size data training dan testing
print('train size', len(df_tr))
print('test size', len(df_te))
print('valid size', len(df_valid))

# Gabungkan DataFrame df_tr dan df_te
df_all = pd.concat([df_tr, df_te, df_valid], ignore_index=True)

print('===================================================== \n')
print(df_all.groupby(['set', 'labels']).size(), '\n')
print('===================================================== \n')

# Cek sample data
print(df_all.sample(5))

# Memanggil dataset asli yang berisi keseluruhan data gambar yang sesuai dengan labelnya
datasource_path = "drive/MyDrive/Dataset"
# Membuat variabel Dataset, dimana nanti menampung data yang telah dilakukan pembagian data training dan testing
dataset_path = "Dataset-Final/"

# First, ensure a clean slate by removing the existing dataset directory
if os.path.exists(dataset_path):
    shutil.rmtree(dataset_path)
    print(f"Removed existing directory: {dataset_path}")

for index, row in tq(df_all.iterrows()):
    # Deteksi filepath
    file_path = row['path']
    # The 'image' column likely doesn't exist. Using 'file_name' which is present in the df.
    # Also, ensure 'datasource_path' is only used if 'file_path' itself is not valid.
    if not os.path.exists(file_path):
            file_path = os.path.join(datasource_path, row['labels'], row['file_name'])

    # Buat direktori tujuan folder
    destination_dir = os.path.join(dataset_path,row['set'],row['labels'])
    if not os.path.exists(destination_dir):
        os.makedirs(destination_dir)

    # Tentukan tujuan file
    destination_file_name = os.path.basename(file_path)
    file_dest = os.path.join(destination_dir, destination_file_name)

    # Salin file dari sumber ke tujuan
    if not os.path.exists(file_dest):
        shutil.copy2(file_path,file_dest)

# Define training and test directories
TRAIN_DIR = "Dataset-Final/train"
TEST_DIR = "Dataset-Final/test"
VALID_DIR = "Dataset-Final/validation"

# Update directory names to match the dataset
train_normal = os.path.join(TRAIN_DIR + '/Normal')
# train_pneumonia = os.path.join(TRAIN_DIR + '/Pneumonia') # Removed: Pneumonia class does not exist
train_tuberculosis = os.path.join(TRAIN_DIR + '/Tuberculosis')

test_normal = os.path.join(TEST_DIR + '/Normal')
# test_pneumonia = os.path.join(TEST_DIR + '/Pneumonia') # Removed: Pneumonia class does not exist
test_tuberculosis = os.path.join(TEST_DIR + '/Tuberculosis')

valid_normal = os.path.join(VALID_DIR + '/Normal')
# valid_pneumonia = os.path.join(VALID_DIR + '/Pneumonia') # Removed: Pneumonia class does not exist
valid_tuberculosis = os.path.join(VALID_DIR + '/Tuberculosis')


print("Total number of Normal images in training set: ",len(os.listdir(train_normal)))
# print("Total number of Pneumonia images in training set: ",len(os.listdir(train_pneumonia))) # Removed
print("Total number of Tuberculosis images in training set: ",len(os.listdir(train_tuberculosis)))

print("Total number of Normal images in testing set: ",len(os.listdir(test_normal)))
# print("Total number of Pneumonia images in testing set: ",len(os.listdir(test_pneumonia))) # Removed
print("Total number of Tuberculosis images in testing set: ",len(os.listdir(test_tuberculosis)))

print("Total number of Normal images in validation set: ",len(os.listdir(valid_normal)))
# print("Total number of Pneumonia images in validation set: ",len(os.listdir(valid_pneumonia))) # Removed
print("Total number of Tuberculosis images in validation set: ",len(os.listdir(valid_tuberculosis)))

from tensorflow.keras.preprocessing.image import ImageDataGenerator

# Image size harus sama dengan input MobileNetV2 (150x150 dalam kasus ini)
IMG_SIZE = (150, 150)
BATCH_SIZE = 32

# Data augmentation + validation split untuk train & val
datagen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2,
    rotation_range=20,
    width_shift_range=0.1,
    height_shift_range=0.1,
    shear_range=0.1,
    zoom_range=0.1,
    horizontal_flip=True,
    fill_mode='nearest'
)

train_generator = datagen.flow_from_directory(
    TRAIN_DIR,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    subset='training',  # subset untuk training
    shuffle=True
)

validation_generator = datagen.flow_from_directory(
    TRAIN_DIR,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    subset='validation',  # subset untuk validasi
    shuffle=False
)

test_datagen = ImageDataGenerator(rescale=1. / 255)

test_generator = test_datagen.flow_from_directory(
    TEST_DIR,
    target_size=IMG_SIZE,
    batch_size=1,
    class_mode='categorical',
    shuffle=False
)

train_datagen = ImageDataGenerator(rescale=1. / 255,
                                   shear_range=0.2,
                                   zoom_range=0.2,
                                   horizontal_flip=True)
val_datagen = ImageDataGenerator(rescale=1. / 255,
                                 shear_range=0.2,
                                 zoom_range=0.2,
                                 horizontal_flip=True)
test_datagen = ImageDataGenerator(rescale=1. / 255,
                                  shear_range=0.2,
                                  zoom_range=0.2,
                                  horizontal_flip=True)

"""# Modelling"""

from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.layers import Conv2D, BatchNormalization, MaxPooling2D, Flatten, Dense, Dropout
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
import tensorflow as tf

# Load pretrained base model (MobileNetV2)
# We will use the model as a feature extractor
base_model = MobileNetV2(input_shape=(150, 150, 3),
                         include_top=False,  # Exclude the classification layer
                         weights='imagenet') # Load weights pre-trained on ImageNet

# Freeze the layers of the base model
# This prevents their weights from being updated during training
base_model.trainable = False

# Create a new model on top of the base model
x = base_model.output # Get the output tensor of the base model
x = tf.keras.layers.GlobalAveragePooling2D()(x) # Add a Global Average Pooling layer
x = Dense(128, activation='relu')(x) # Add a dense layer
x = Dropout(0.5)(x) # Add dropout for regularization
output = Dense(2, activation='softmax')(x) # Add the final classification layer for 2 classes

# Define the new model
model = Model(inputs=base_model.input, outputs=output)

# Compile the model
model.compile(optimizer=Adam(learning_rate=1e-4),
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# Display the model summary
model.summary()

# Compile the model
print('Compiling Model')
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model_viz = tf.keras.utils.plot_model(model,
                          to_file='model.png',
                          show_shapes=True,
                          show_layer_names=True,
                          rankdir='TB',
                          expand_nested=True,
                          dpi=55)
model_viz

callbacks = [
    EarlyStopping(patience=5, restore_best_weights=True)
]

# Menggunakan direktori yang benar sesuai dataset
count_normal = len(os.listdir(train_normal))
# count_pneumonia = len(os.listdir(train_pneumonia)) # Removed: Pneumonia class does not exist
count_tuberculosis = len(os.listdir(train_tuberculosis))

# Menghitung weight untuk setiap kelas (untuk 2 kelas)
total_samples = count_normal + count_tuberculosis
weight_0 = (1 / count_normal) * (total_samples / 2.0) # For 'Normal'
weight_1 = (1 / count_tuberculosis) * (total_samples / 2.0) # For 'Tuberculosis'


# Membuat dictionary untuk class_weight
# Pastikan urutan index sesuai dengan label pada generator (Normal=0, Tuberculosis=1)
# Anda bisa cek urutan label pada generator dengan train_generator.class_indices
# Assuming train_generator.class_indices is {'Normal': 0, 'Tuberculosis': 1}
class_weights = {0: weight_0, 1: weight_1}

history_1 = model.fit(
    train_generator,
    validation_data=validation_generator,
    epochs=50,
    callbacks=callbacks,
    class_weight=class_weights
)

"""# Evaluation"""

test_loss, test_acc = model.evaluate(test_generator)
print(f"Test Accuracy: {test_acc:.2f}")

acc = history_1.history['accuracy']
val_acc = history_1.history['val_accuracy']
loss = history_1.history['loss']
val_loss = history_1.history['val_loss']

epochs = range(len(acc))

plt.plot(epochs, acc, 'r')
plt.plot(epochs, val_acc, 'b')
plt.title('Training and Validation Accuracy')
plt.ylabel('accuracy')
plt.xlabel('epoch')
plt.legend(['train', 'val'], loc='upper left')
plt.show()

plt.plot(epochs, loss, 'r')
plt.plot(epochs, val_loss, 'b')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['train', 'val'], loc='upper left')
plt.title('Training and Validation Loss')
plt.show()

test_generator.reset()

preds_1 = model.predict(test_generator, verbose=0)
preds_1 = np.argmax(preds_1, axis=1)

# Print Confusion Matrix
cm = pd.DataFrame(data=confusion_matrix(test_generator.classes, preds_1),
                  index=["Actual Normal", "Actual Tuberculosis"],
                  columns=["Predicted Normal", "Predicted Tuberculosis"])
sns.heatmap(cm,annot=True,fmt="d")

# Print Classification Report
print("\n")
print(classification_report(y_true=test_generator.classes,y_pred=preds_1,target_names =['Normal','Tuberculosis'], digits=4))

"""# Convert Model"""

# @title
# Konversi ke Saved_model
model.export('saved_model')

# @title
# Cek apakah folder saved_model dan isinya sudah disimpan
if os.path.exists('saved_model'):
    print("Model saved in 'saved_model' folder.")
    print("Contents of 'saved_model':", os.listdir('saved_model'))
else:
    print("Model not saved.")

# @title
# Konversi ke TFLite
converter = tf.lite.TFLiteConverter.from_saved_model("saved_model")
converter.experimental_new_converter = True
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
tflite_model = converter.convert()

# Simpan model.tflite
os.makedirs("tflite", exist_ok=True)
with open("tflite/model.tflite", "wb") as f:
    f.write(tflite_model)

# Simpan label.txt
labels = ["Normal", "Tuberculosis"]
with open("tflite/label.txt", "w") as f:
    for label in labels:
        f.write(label + "\n")

# @title
os.makedirs('tfjs_model', exist_ok=True)
model.save("tfjs_model/model.h5")

# @title
!pip install tensorflowjs

# @title
import tensorflow as tf
import tensorflowjs as tfjs

# Load model dari .h5
model = tf.keras.models.load_model('tfjs_model/model.h5')

# Save ke format TensorFlow.js
tfjs.converters.save_keras_model(model, 'tfjs_model')

"""# Testing"""

import textwrap
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image
from google.colab import files
from IPython.display import display, Markdown

# Load model
model = load_model('tfjs_model/model.h5')  # Uncomment this line and replace 'model.h5' if you saved your model

# Label kelas (sesuai dengan urutan kelas di generator)
class_labels = ['Normal', 'Tuberculosis']

# Saran berdasarkan prediksi
treatment_suggestions = {
    'Normal': "Hasil prediksi menunjukkan kemungkinan paru-paru normal. Namun, penting untuk diingat bahwa diagnosis medis harus dilakukan oleh profesional kesehatan berdasarkan pemeriksaan menyeluruh, riwayat medis, dan hasil tes lainnya. Citra X-ray hanyalah salah satu alat bantu diagnostik. Lanjutkan pola hidup sehat dan jadwalkan pemeriksaan kesehatan rutin sesuai anjuran dokter.",
    'Tuberculosis': "Hasil prediksi menunjukkan kemungkinan adanya Tuberculosis. Ini memerlukan perhatian medis segera. Silakan segera konsultasikan hasil ini dengan dokter atau profesional kesehatan. Diagnosis pasti TB memerlukan pemeriksaan tambahan seperti tes dahak dan mungkin tes lainnya. Pengobatan TB biasanya melibatkan kombinasi antibiotik selama beberapa bulan dan harus diawasi oleh profesional medis."
}

# Upload gambar dari user
uploaded = files.upload()

for file_name in uploaded.keys():
    # Load dan preprocess gambar
    img = image.load_img(file_name, target_size=(150, 150))
    img_array = image.img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0)
    img_array = img_array / 255.0

    # Prediksi
    prediction = model.predict(img_array)
    predicted_class = np.argmax(prediction, axis=1)[0]
    predicted_label = class_labels[predicted_class]

    # Output
    print(f"\nGambar: {file_name}")
    print(f"Prediksi: {predicted_label}")
    print(f"Probabilitas: {prediction}")
    # Tambahkan enter dan buat heading tebal
    display(Markdown("\n\n**Saran:**"))

    # Wrap dan tampilkan isi saran
    if predicted_label in treatment_suggestions:
        wrapped_text = textwrap.fill(treatment_suggestions[predicted_label], width=100)
        print(wrapped_text)
    else:
        print("Saran tidak tersedia untuk kelas ini.")


    # Tampilkan gambar
    plt.imshow(img)
    plt.title(f"Prediksi: {predicted_label}")
    plt.axis('off')
    plt.show()

"""# Metode SHAP"""

!pip install shap

"""### SHAP Explainer Setup

Sel ini akan menginisialisasi SHAP `GradientExplainer` menggunakan model yang sudah dilatih dan sebagian kecil data pelatihan sebagai *background data*. Ini perlu dijalankan satu kali sebelum Anda melakukan *testing* dengan visualisasi SHAP.
"""

import shap
import numpy as np

# Ensure model and train_generator are defined and available
# (Assuming cells PB-Y9irtzaH- and 1AZukFLTzEzo, LYGTL0iOzk9N have been run)

# Prepare background data for SHAP Explainer
print("Preparing background data for SHAP GradientExplainer...")

train_generator.reset()
background_images_list = []
num_batches_for_background = 4

for _ in range(num_batches_for_background):
    batch_images, _ = next(train_generator)
    background_images_list.append(batch_images)

background_data = np.concatenate(background_images_list, axis=0)

# Use a smaller random sample if too much data
if background_data.shape[0] > 100:
    indices = np.random.choice(background_data.shape[0], 100, replace=False)
    background_data = background_data[indices]

print(f"Shape of background data: {background_data.shape}")

# Initialize SHAP GradientExplainer
print("Initializing SHAP GradientExplainer...")
# 'model' variable is assumed to be globally available from previous cells.
explainer_shap = shap.GradientExplainer(model, background_data)
print("SHAP GradientExplainer initialized.")

import textwrap
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image
from google.colab import files
from IPython.display import display, Markdown
import shap # Import shap for explanation

# Load model
model = load_model('tfjs_model/model.h5')  # Uncomment this line and replace 'model.h5' if you saved your model

# Label kelas (sesuai dengan urutan kelas di generator)
# Corrected class_labels to match the 2-output model
class_labels = ['Normal', 'Tuberculosis']

# Saran berdasarkan prediksi
treatment_suggestions = {
    'Normal': "Hasil prediksi menunjukkan kemungkinan paru-paru normal. Namun, penting untuk diingat bahwa diagnosis medis harus dilakukan oleh profesional kesehatan berdasarkan pemeriksaan menyeluruh, riwayat medis, dan hasil tes lainnya. Citra X-ray hanyalah salah satu alat bantu diagnostik. Lanjutkan pola hidup sehat dan jadwalkan pemeriksaan kesehatan rutin sesuai anjuran dokter.",
    'Tuberculosis': "Hasil prediksi menunjukkan kemungkinan adanya Tuberculosis. Ini memerlukan perhatian medis segera. Silakan segera konsultasikan hasil ini dengan dokter atau profesional kesehatan. Diagnosis pasti TB memerlukan pemeriksaan tambahan seperti tes dahak dan mungkin tes lainnya. Pengobatan TB biasanya melibatkan kombinasi antibiotik selama beberapa bulan dan harus diawasi oleh profesional medis."
}

# Upload gambar dari user
uploaded = files.upload()

for file_name in uploaded.keys():
    # Load dan preprocess gambar
    img = image.load_img(file_name, target_size=(150, 150))
    img_array = image.img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0)
    img_array = img_array / 255.0

    # Prediksi
    prediction = model.predict(img_array)
    predicted_class_index = np.argmax(prediction, axis=1)[0]
    predicted_label = class_labels[predicted_class_index]

    # Output Prediksi
    print(f"\nGambar: {file_name}")
    print(f"Prediksi: {predicted_label}")
    print(f"Probabilitas: {prediction[0]}")

    # Tampilkan Saran
    display(Markdown("\n\n**Saran:**"))
    if predicted_label in treatment_suggestions:
        wrapped_text = textwrap.fill(treatment_suggestions[predicted_label], width=100)
        print(wrapped_text)
    else:
        # Ensure 'Pneumonia' is only suggested if it's a predicted class, which it isn't with 2 outputs.
        # If the model could predict Pneumonia, it would need 3 output units.
        # For now, it only predicts Normal or Tuberculosis.
        # The prediction for the uploaded image was 'Pneumonia' which indicates a potential issue
        # in how `class_labels` was used or the model's actual outputs vs what was expected.
        # With a 2-class model (Normal, Tuberculosis), a prediction of 'Pneumonia' is impossible.
        # It seems the previous `predicted_label = class_labels[predicted_class_index]` was incorrect
        # because `class_labels` had 3 elements but `predicted_class_index` was 0 or 1.
        # The `predicted_label` will now correctly be either 'Normal' or 'Tuberculosis'.
        print("Saran tidak tersedia untuk kelas ini.")

    # Tampilkan gambar asli dengan prediksi
    plt.figure(figsize=(10, 5))
    plt.subplot(1, 2, 1) # One row, two columns, first plot
    plt.imshow(img)
    plt.title(f"Gambar Asli\nPrediksi: {predicted_label}")
    plt.axis('off')

    # --- SHAP Explanation for the predicted class ---
    # Ensure 'explainer_shap' is defined from the setup cell before running this
    if 'explainer_shap' in locals():
        print(f"\nCalculating SHAP values for predicted class: {predicted_label}...")
        shap_values_list = explainer_shap.shap_values(img_array)

        # GradientExplainer can return a list of arrays (one per output) or a single array
        # if the model output is a single tensor representing all classes.
        if isinstance(shap_values_list, list):
            # This is the common case: list of N_CLASSES arrays, each of shape (1, H, W, C)
            shap_values_for_plot = shap_values_list[predicted_class_index][0] # [0] to remove batch dimension
        else:
            # This handles cases where shap_values_list is a single array,
            # potentially with the class dimension at the end.
            # Assuming shape (1, H, W, C, N_CLASSES)
            # We need to select the batch item first (index 0), then slice for the class dimension
            shap_values_for_plot = shap_values_list[0, ..., predicted_class_index]

        #plt.subplot(1, 2, 2) # One row, two columns, second plot
        shap.image_plot(
            shap_values_for_plot,                                 # Now this is (H, W, C)
            img_array[0],                                 # The original image (first element of batch)
            show=False,                                   # Prevent shap.image_plot from calling plt.show() prematurely
            # Uncomment if you want to explicitly label the plot for the predicted class
            labels=[predicted_label] # Use the correct predicted label
        )
        plt.title(f"SHAP for '{predicted_label}'")
        plt.axis('off')
    else:
        print("\nSHAP Explainer (explainer_shap) not initialized. Please run the SHAP Explainer Setup cell first.")

    #plt.tight_layout()
    plt.show()

from google.colab import files
from PIL import Image
import matplotlib.pyplot as plt
import numpy as np # Import numpy for potential array operations if needed, though PIL and matplotlib can handle images directly

# 2. Use files.upload() to create an upload widget
uploaded = files.upload()

for file_name in uploaded.keys():
    # 3. Get the filename of the uploaded image
    print(f"Uploaded file: {file_name}")

    # 4. Load the uploaded image using Image.open() and resize it
    img = Image.open(file_name)
    # Ensure consistent channel format (e.g., RGB) if image is RGBA or grayscale initially
    if img.mode != 'RGB':
        img = img.convert('RGB')

    # Resize to a consistent dimension (e.g., 224x224 pixels or 150x150 to match model input)
    # Using 150x150 as it matches the model's expected input size
    target_size = (150, 150)
    img_resized = img.resize(target_size)

    # 5. Display the resized image using plt.imshow()
    plt.figure(figsize=(6, 6))
    plt.imshow(img_resized)

    # 6. Add a title to the plot
    plt.title('Uploaded Image for Annotation')

    # 7. Turn off the axis ticks and labels
    plt.axis('off')

    # 8. Show the plot
    plt.show()

    # Optionally, you can also display the original image to compare
    plt.figure(figsize=(6, 6))
    plt.imshow(img)
    plt.title('Original Uploaded Image')
    plt.axis('off')
    plt.show()

import tensorflow as tf
from IPython.display import Image, display

# Ensure 'model' is defined from previous cells
# If not, it needs to be loaded or rebuilt

# Generate the model visualization
model_viz_path = 'model_architecture.png'
model_viz = tf.keras.utils.plot_model(model,
                          to_file=model_viz_path,
                          show_shapes=True,
                          show_layer_names=True,
                          rankdir='TB',
                          expand_nested=True,
                          dpi=55)

# Display the generated image in the notebook
display(Image(filename=model_viz_path))

"""# **Download Model Data**"""

!zip -r capstone.zip /content/saved_model/ /content/tfjs_model/ /content/tflite/ /content/Dataset-Final/

!ls /content

from google.colab import files
files.download('capstone.zip')